#!/usr/bin/env bash

# Flags:
#
# r: region
# f: fullscreen

# $1 - created tmpfile
screenshot_actions () {
  tmpfile=$1
  wl-copy < $tmpfile
  action=$(dunstify --icon=$tmpfile "Screenshot copied" -A "default,Edit" -A "save,Save")
  
  if [[ "$action" != "1" ]] || [[ "$action" != "2" ]]; then
    case $action in
      default)
        swappy -f $tmpfile
        ;;
      save)
        imgfile=$XDG_SCREENSHOTS_DIR/"screenshot-$(date +"%s.png")"
        cp $tmpfile $imgfile
    esac
  fi

  rm "$tmpfile"
}

if [[ "$1" == "r" ]]; then
  tmpfile=$(mktemp /tmp/grim-img-XXXXXX)

  grim -g "$(slurp)" $tmpfile
  screenshot_actions $tmpfile

elif [[ $1 == rf ]]; then
  filename="screenshot_$(date +"%s.png")"
  imgfile=$XDG_SCREENSHOTS_DIR/$filename
  
  grim -g "$(slurp)" $imgfile
  dunstify --icon=$imgfile "Screenshot saved"

elif [[ "$1" == "f" ]]; then
  tmpfile=$(mktemp /tmp/grim-img-XXXXXX)

  grim $tmpfile
  screenshot_actions $tmpfile
fi
