#!/usr/bin/env bash

# Flags:
#
# r: region
# f: fullscreen

# $1 - created tmpfile
screenshot_actions () {
  tmpfile=$1
  wl-copy < $tmpfile
  action=$(dunstify --icon=$tmpfile "Screenshot copied" -A "default,Edit" -A "save,Save")
  
  if [[ "$action" != "1" ]] || [[ "$action" != "2" ]]; then
    case $action in
      default)
        swappy -f $tmpfile
        ;;
      save)
        imgfile="$XDG_SCREENSHOTS_DIR/screenshot-$(date +"%s.png")"
        dunstify "$imgfile" "imgfile"
        cp $tmpfile $imgfile &> $HOME/log
        dunstify $?
    esac
  fi

  rm "$tmpfile"
}

if [[ "$1" == "r" ]]; then
  tmpfile=$(mktemp /tmp/grim-img-XXXXXX)

  if grim -g "$(slurp)" $tmpfile; then
    screenshot_actions $tmpfile
  else
    rm "$tmpfile"
    exit 1
  fi

elif [[ "$1" != "r" ]]; then
  tmpfile=$(mktemp /tmp/grim-img-XXXXXX)

  if grim $tmpfile; then
    screenshot_actions $tmpfile
  else
    rm "$tmpfile"
    exit 1
  fi

  rm "$tmpfile"

fi
